services:
  - type: web
    name: fluid-backend
    env: python
    rootDir: backend
    plan: free
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

  - type: static
    name: fluid-frontend
    rootDir: frontend/static
    buildCommand: ""
    staticPublishPath: .
